RuqsatAl/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from RuqsatAl import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),
    path('movies/', MovieView.as_view(), name='movies'),
    path('search/movie', search_movie_by_name, name='movie'),
    path('search/genre/<int:pk>', search_movie_by_genre, name='movies_genre'),
    path('movie_detail/<int:pk>', movie_detail, name='movie_detail'),
    path('profile/', profile, name='profile'),
    path('favorites/<int:id>/', addToFavorites, name='addtofavs'),
    path('booking/<int:pk>', booking, name='booking'),
    path('select_seat/<int:pk>', select_seat, name='select_seat'),
    path('seat_seal/<int:pk>', seat_seal, name='seat_seal'),
    path('select_seat/topay', to_pay, name='topay'),
]

main/models.py
from msilib.schema import Class
from statistics import mode
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=150)
    price = models.IntegerField(default=None)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Hall(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Hall'
        verbose_name_plural = 'Halls'


class Seat(models.Model):
    row = models.IntegerField()
    number = models.IntegerField()

    def __str__(self):
        return str(self.row) + '_' + str(self.number)

    class Meta:
        verbose_name = 'Seat'
        verbose_name_plural = 'Seats'


class Genres(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Genre'
        verbose_name_plural = 'Genres'


class Movie(models.Model):
    title = models.CharField(max_length=150)
    original_title = models.CharField(max_length=150)
    original_language = models.CharField(max_length=150)
    overview = models.TextField(null=True)
    popularity = models.FloatField(null=True)
    poster_path = models.CharField(null=True, max_length=500)
    release_date = models.DateField(null=True, max_length=150)
    vote_average = models.FloatField(null=True)
    vote_count = models.IntegerField(null=True)
    genres = models.ManyToManyField(Genres)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Movie'
        verbose_name_plural = 'Movies'


class Admin(BaseUserManager):
    pass


class User(AbstractUser):

    def __str__(self):
        return self.username


class Session(models.Model):
    date = models.DateField(default=None)
    time = models.TimeField(default=None)
    hall = models.ForeignKey('Hall', models.CASCADE)
    movie = models.ForeignKey('Movie', models.CASCADE)

    def __str__(self):
        return self.movie.title + ' ' + str(self.date) + ' ' + str(self.time)

    class Meta:
        verbose_name = 'Session'
        verbose_name_plural = 'Sessions'


class Booking(models.Model):
    session = models.ForeignKey('Session', models.CASCADE)
    seat = models.ManyToManyField('Seat')
    user = models.ForeignKey('User', models.CASCADE)
    booked_datetime = models.DateTimeField(default=None)
    qr_code = models.ImageField()
    is_paied = models.BooleanField(default=False)
    is_guest_came = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'Booking'
        verbose_name_plural = 'Bookings'


class Favorites(models.Model):
    movie = models.ForeignKey('Movie', models.CASCADE)
    user = models.ForeignKey('User', models.CASCADE)

    class Meta:
        verbose_name = 'Favorite'
        verbose_name_plural = 'Favorites'

    def __str__(self):
        return self.user.username + ' ' + self.movie.title


class Comment(models.Model):
    user = models.ForeignKey('User', models.CASCADE)
    message = models.TextField()
    movie = models.ForeignKey('Movie', models.CASCADE)
    datetime = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Commnets'

    def __str__(self) -> str:
        return str(self.user) + ' ' + str(self.movie)

main/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import *
from .models import *
from .utils import embed_QR


class HomeView(ListView):
    model = Movie
    template_name = 'main/index.html'
    genres = Genres.objects.all()
    popular_movies = Movie.objects.all().order_by('vote_average')[:4]
    new_movies = Movie.objects.all().order_by('-release_date')[:19]

    def get_context_data(self, genres=genres, popular_movies=popular_movies,
                         new_movies=new_movies, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Home'
        context['genres'] = genres
        context['new_movies'] = new_movies
        context['popular_movies'] = popular_movies
        return context


class MovieView(ListView):
    model = Movie
    template_name = 'main/movies.html'
    genres = Genres.objects.all()
    recent = Movie.objects.all().order_by('-release_date')[:6]
    popular = Movie.objects.all().order_by('-vote_average')[:6]
    Trend = Movie.objects.all().order_by('-popularity')[:6]
    paginate_by = 12

    def get_context_data(self, genres=genres, recent=recent, popular=popular, trend=Trend, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_anonymous:
            favs = Favorites.objects.all()
        else:
            favs = Favorites.objects.filter(
                user=self.request.user).values_list('movie__title', flat=True)
        context['title'] = 'Movies'
        context['genres'] = genres
        context['recent'] = recent
        context['popular'] = popular
        context['trend'] = trend
        context['favs'] = favs
        return context


def search_movie_by_genre(request, pk):
    genre = Genres.objects.get(pk=pk)
    movies = Movie.objects.all()
    genres = Genres.objects.all()
    context = {
        'title': genre,
        'movies': movies,
        'genres': genres
    }
    return render(request, 'main/movie_genre.html', context)


def search_movie_by_name(request):
    genres = Genres.objects.all()
    title = request.GET.get('search')
    movies = Movie.objects.filter(title__contains=title)
    context = {
        'title': 'Searching: ' + title,
        'movies': movies,
        'genres': genres
    }
    return render(request, 'main/movie_search.html', context)


def movie_detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    comments = Comment.objects.filter(movie=movie)
    genres = Genres.objects.all()
    movie_genres = movie.genres.values()

    if request.method == 'POST':
        user = User.objects.get(id=request.user.id)
        message = request.POST.get('comment')

        comment = Comment.objects.create(
            user=user, movie=movie, message=message)
        if comment.save():
            return redirect('movie_detail', id)

    context = {
        'title': movie.title,
        'movie': movie,
        'movie_genres': movie_genres,
        'genres': genres,
        'comments': comments
    }

    return render(request, 'main/movie_detail.html', context)


def contact(request):
    if request.method == 'POST':
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        msg = request.POST.get('msg')

        data = {
            'fname': fname,
            'lname': lname,
            'email': email,
            'subject': subject,
            'msg': msg
        }
        message = f'''
        New message:{data['msg']}
        From : {data['email']}
        '''
        send_mail(subject, message, '', ['solizholdasbai@gmail.com'])

    context = {
        'title': 'Contact Us'
    }
    return render(request, 'main/contact.html', context)


def about(request):
    movies = Movie.objects.count()
    admins = User.objects.filter(is_staff=True).count()
    users = User.objects.all().count()
    context = {'title': 'About',
               'movie_count': movies,
               'staff_count': admins,
               'users': users}
    return render(request, 'main/about.html', context)


@login_required(login_url='login')
def addToFavorites(request, id):
    movie = Movie.objects.get(id=id)
    user = User.objects.get(id=request.user.id)
    if not Favorites.objects.all().filter(user=user, movie=movie):
        try:
            Favorites.objects.create(user=user, movie=movie)
        except:
            return redirect('home')
    else:
        try:
            m = Favorites.objects.all().filter(user=user, movie=movie)
            m.delete()
        except:
            return redirect('home')
    return redirect('movies')


@login_required
def profile(request):
    favs = Favorites.objects.all().filter(user=request.user)
    tickets = Booking.objects.all().filter(user=request.user)
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        user = User.objects.get(id=request.user.id)
        user.first_name = first_name
        user.last_name = last_name
        user.email = email
        user.phone = phone
        print(user.last_name)
        if user.save():
            messages.error(request, 'Updated Successfully!')
            return redirect('profile')
        else:
            messages.error(request, 'Please try again')

    context = {'title': 'Profile',
               'favs': favs,
               'tickets': tickets
               }
    return render(request, 'main/profile.html', context)


@login_required
def booking(request, pk):
    sessions = Session.objects.filter(movie_id=pk).values()
    dates = sessions.values_list('date', flat=True).distinct('date')

    context = {
        'title': 'Booking',
        'sessions': sessions,
        'dates': dates
    }

    return render(request, 'main/booking.html', context)


@login_required
def select_seat(request, pk):
    session = Session.objects.get(pk=pk)
    context = {
        'title': 'Seat Selection',
        'session': session
    }
    return render(request, 'main/select_seat.html', context)


@login_required
def seat_seal(request, pk):
    session = Session.objects.get(pk=pk)
    sold_seats = Booking.objects.filter(
        session__pk=pk).values_list('seat', flat=True)
    s = list(sold_seats)
    ssss = Seat.objects.filter(id__in=s)

    context = {
        'title': 'Booking',
        'sold_seats': ssss,
        'session': session
    }

    return render(request, 'main/seat_sel.html', context)


@login_required
def to_pay(request):
    if request.method == 'POST':
        ids = []
        seats_selected = request.POST['seats'].split(',')
        seats = Seat.objects.all()
        for i in seats_selected:
            ids.append(
                seats.get(row=int(i[:i.find('_')]), number=int(i[i.find('_') + 1:])))
        user = User.objects.get(id=request.user.id)
        session = Session.objects.get(id=int(request.POST['session_id']))
        b = Booking.objects.create(
            user=user, session=session, is_paied=True, booked_datetime=datetime.datetime.now())
        b.seat.set(ids)
        embed_QR(str(b.pk))
        b.qr_code = f'{b.pk}.png'
        b.save()
        return JsonResponse(data={'ans': 'success'})

main/templates/main/Contact_Us.html
{% extends 'main/layout.html' %}
{% load static %}
{% block content %}
    {% block style %}
        <link rel="stylesheet" type="text/css" href="{% static 'assets/css/contact_us.css' %}">
    {% endblock %}
    <!-- Contact Us Form -->
    <div class="container">
        <h4>Contact Us</h4>
        <h3>Leave a Message</h3>
        <p>If you have a question regarding our services,
            feel free to contact us using the form below.</p>

        <form name="contact-us-form" method="POST" action="">
            {% csrf_token %}
            <div class="row100" id="fname-row100">
                <div class="col">
                    <div class="inputBox" id="fname-inputBox">
                        <label>
                            <input type="text" name="fname" placeholder="First Name"/>
                        </label>
                        <span class="line" id="fname-line"></span>
                    </div>
                </div>
                <div class="col">
                    <div class="inputBox" id="lname-inputBox">
                        <label>
                            <input type="text" name="lname" placeholder="Last Name"/>
                        </label>
                        <span class="line" id="lname-line"></span>
                    </div>
                </div>
            </div>
            <div class="row100" id="email-row100">
                <div class="col">
                    <div class="inputBox" id="email-inputBox">
                        <label>
                            <input type="email" name="email" pattern="[^ @]*@[^ @]*" placeholder="Email" />
                        </label>
                        <span class="line" id="email-line"></span>
                    </div>
                </div>
                <div class="col">
                    <div class="inputBox" id="tel-inputBox">
                        <label>
                            <input type="tel" name="subject" placeholder="Subject" />
                        </label>
                        <span class="line" id="tel-line"></span>
                    </div>
                </div>
            </div>
            <div class="row100">
                <div class="col">
                    <div class="inputBox textarea">
                        <label>
                            <textarea name="msg" placeholder="Type your message Here..."></textarea>
                        </label>
                        <span class="line"></span>
                    </div>
                </div>
            </div>
            <div class="row100">
                <div class="col">
                    <div class="submitbutton">
                        <button class="btn submitbtn" type="submit">Submit</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

main/templates/main/about.html
{% extends 'main/layout.html' %}
{% load static %}
{% block content %}
    <!-- /about-->
    <div class="w3l-ab-grids py-5">
        <div class="container py-lg-4">
            <div class="row ab-grids-sec align-items-center">
                <div class="col-lg-6 ab-right">
                    <img class="img-fluid" src="../../static/assets/images/banner1.jpg" alt="">
                </div>
                <div class="col-lg-6 ab-left pl-lg-4 mt-lg-0 mt-5">
                    <h3 class="hny-title">RuqsatAl Entertainment</h3>
                    <p class="mt-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam id quisquam ipsam
                        molestiae ad eius accusantium? Nulla dolorem perferendis inventore! posuere cubilia Curae;
                        Nunc non risus in justo convallis feugiat.</p>
                </div>
            </div>

            <div class="w3l-counter-stats-info text-center">
                <div class="stats_left">
                    <div class="counter_grid">
                        <div class="icon_info">
                            <p class="counter">{{ movie_count }}</p>
                            <h4>Movies</h4>

                        </div>
                    </div>
                </div>
                <div class="stats_left">
                    <div class="counter_grid">
                        <div class="icon_info">
                            <p class="counter">165</p>
                            <h4>Shows</h4>

                        </div>
                    </div>
                </div>
                <div class="stats_left">
                    <div class="counter_grid">
                        <div class="icon_info">
                            <p class="counter">{{ staff_count }}</p>
                            <h4>Staff Members</h4>

                        </div>
                    </div>
                </div>
                <div class="stats_left">
                    <div class="counter_grid">
                        <div class="icon_info">
                            <p class="counter">{{ users }}</p>
                            <h4>No. of Users</h4>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

main/templates/main/check.html
{% extends 'main/layout.html' %}
{% load static %}
{% block style %}
{% endblock style %}
{% block content %}
<div class="container">
    {% if result %}
    <div class="content">
        <img src="{% static 'assets/fonts/check-solid.svg' %}">
    </div>
    {% else %}
    <div class="content">
        <img src="{% static 'assets/fonts/xmark-solid.svg' %}">
    </div>
    {% endif %}
</div>
{% endblock content %}
{% block scripts %}
{% endblock %}

main/templates/main/movie_search.html
{% extends 'main/layout.html' %}
{% load static %}
{% block content %}
    <!--grids-sec1-->
    <section class="w3l-grids">
        <div class="grids-main py-5">
            <div class="container py-lg-4">
                <div class="headerhny-title">
                    <div class="w3l-title-grids">
                        <div class="headerhny-left">
                            <h3 class="hny-title">{{ title }}</h3>
                        </div>
                    </div>
                </div>
                <div class="w3l-populohny-grids">
                    {% for movie in movies %}
                        {% if movie.poster_path %}
                        <div class="item vhny-grid">
                            <div class="box16 mb-0">
                                <a href="{% url 'movie_detail' pk=movie.pk %}">
                                    <figure>
                                        <img class="img-fluid" src="{{ movie.poster_path }}" alt="">
                                    </figure>
                                    <div class="box-content">
                                        <h3 class="title">{{ movie.title }}</h3>
                                        <h4> <span class="post"><span class="fa fa-calendar"> </span> {{ movie.release_date }}</span>
                                            <span class="post fa fa-heart-o text-right"></span>
                                        </h4>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

main/templates/main/movies.html
{% extends 'main/layout.html' %}
{% load static %}
{% block content %}
    <!--grids-sec1-->
    <section class="w3l-grids">
        <div class="grids-main py-5">
            <div class="container py-lg-4">
                <div class="headerhny-title">
                    <div class="w3l-title-grids">
                        <div class="headerhny-left">
                            <h3 class="hny-title">All</h3>
                        </div>
                    </div>
                </div>
                <div class="w3l-populohny-grids">
                    {% for movie in movie_list %}
                        <div class="item vhny-grid">
                            <div class="box16 mb-0">
                                <a href="{% url 'movie_detail' pk=movie.pk %}">
                                    <figure>
                                        <img class="img-fluid" src="{{ movie.poster_path }}" alt="">
                                    </figure>
                                    <div class="box-content">
                                        <h3 class="title">{{ movie.title }}</h3>
                                        <h4> <span class="post"><span class="fa fa-calendar"> </span> {{ movie.release_date }}</span>
                                            <a href="{% url 'addtofavs' movie.id %}" class="text-right">
                                                {% if movie.title in favs %}
                                                    <span class="post fa fa-heart text-right"></span>
                                                {% else %}
                                                    <span class="post fa fa-heart-o text-right"></span>
                                                {% endif %}
                                            </a>
                                        </h4>
                                    </div>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <nav>
                    <ul class="pagination pagination-lg justify-content-center">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                        {% endif %}
                        {% for p in paginator.page_range %}
                            {% if page_obj.number == p %}
                            <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </section>

    <section class="w3l-albums py-5" id="projects">
        <div class="container py-lg-4">
            <div class="row">
                <div class="col-lg-12 mx-auto">
                    <!--Horizontal Tab-->
                    <div id="parentHorizontalTab">
                        <ul class="resp-tabs-list hor_1">
                            <li>Recent Movies</li>
                            <li>Popular Movies</li>
                            <li>Trend Movies</li>
                            <div class="clear"></div>
                        </ul>
                        <div class="resp-tabs-container hor_1">
                            <div class="albums-content">
                                <div class="row">
                                    <!--/set1-->
                                    {% for item in recent %}
                                    <div class="col-lg-4 new-relise-gd mt-lg-0 mt-0">
                                        <div class="slider-info">
                                            <div class="img-circle">
                                                <a href="{%  url 'movies' %}">

                                                    <img src="{{ item.poster_path }}" class="img-fluid"
                                                        alt="author image">
                                                    <div class="overlay-icon">

                                                        <span class="fa fa-play video-icon" aria-hidden="true"></span>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="message">
                                                <a class="author-book-title" href="{%  url 'movies' %}">{{ item.title }}</a>
                                                <h4> <span class="post"><span class="fa fa-clock-o"> </span> {{ item.release_date }}</span>
                                                    <a href="{% url 'addtofavs' item.id %}" class="text-right">
                                                        {% if item.title in favs %}
                                                            <span class="post fa fa-heart text-right"></span>
                                                        {% else %}
                                                            <span class="post fa fa-heart-o text-right"></span>
                                                        {% endif %}
                                                    </a>
                                                </h4>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="albums-content">
                                <div class="row">
                                    <!--/set1-->
                                    {% for item in popular %}
                                    <div class="col-lg-4 new-relise-gd mt-lg-0 mt-0">
                                        <div class="slider-info">
                                            <div class="img-circle">
                                                <a href="{%  url 'movies' %}">

                                                    <img src="{{ item.poster_path }}" class="img-fluid"
                                                        alt="author image">
                                                    <div class="overlay-icon">

                                                        <span class="fa fa-play video-icon" aria-hidden="true"></span>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="message">
                                                <a class="author-book-title" href="{%  url 'movies' %}">{{ item.title }}</a>
                                                <h4> <span class="post"><span class="fa fa-clock-o"> </span> {{ item.release_date }}</span>
                                                    <a href="{% url 'addtofavs' item.id %}" class="text-right">
                                                        {% if item.title in favs %}
                                                            <span class="post fa fa-heart text-right"></span>
                                                        {% else %}
                                                            <span class="post fa fa-heart-o text-right"></span>
                                                        {% endif %}
                                                    </a>
                                                </h4>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="albums-content">
                                <div class="row">
                                    <!--/set3-->
                                    {% for item in trend %}
                                    <div class="col-lg-4 new-relise-gd mt-lg-0 mt-0">
                                        <div class="slider-info">
                                            <div class="img-circle">
                                                <a href="{%  url 'movies' %}">
                                                    <img src="{{ item.poster_path }}" class="img-fluid"
                                                        alt="author image">
                                                    <div class="overlay-icon">
                                                        <span class="fa fa-play video-icon" aria-hidden="true"></span>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="message">
                                                <a class="author-book-title" href="{%  url 'movies' %}">{{ item.title }}</a>
                                                <h4> <span class="post"><span class="fa fa-clock-o"> </span> {{ item.release_date }}</span>
                                                    <a href="{% url 'addtofavs' item.id %}" class="text-right">
                                                        {% if item.title in favs %}
                                                            <span class="post fa fa-heart text-right"></span>
                                                        {% else %}
                                                            <span class="post fa fa-heart-o text-right"></span>
                                                        {% endif %}
                                                    </a>
                                                </h4>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}